apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.certificate.name }}
  labels:
    "use-http01-solver": "true"
spec:
  secretName: {{ .Values.certificate.secretname }}
  issuerRef:
    name: {{ .Values.clusterissuer.secretkey }}
    kind: ClusterIssuer
  commonName: {{ .Values.certificate.commonname }}
  dnsNames:
  - {{ .Values.certificate.dnsname }}