apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.clusterissuer.name }}
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: mymail@test.com
    privateKeySecretRef:
      name: {{ .Values.clusterissuer.secretKey }}
    solvers:
      - http01:
          ingress:
            class: {{ .Values.clusterissuer.ingressclass }}