apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.secretProviderClass }}
  namespace: app
spec:
  provider: {{ required "Specify a valid provider." .Values.provider }}
  {{- if .Values.parameters }}
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    userAssignedIdentityID: ""
    keyvaultName: {{ .Values.parameters.keyvaultName }}
    {{- if .Values.parameters.objects }}
    {{- with .Values.parameters.objects }}
    objects:
       {{- toYaml . | nindent 8 }}
     {{- end }}    
    {{- end}}
    tenantId: {{ .Values.parameters.tenantId }}
  {{- end }}
    