apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.secretProviderClass }}
spec:
  provider: {{ required "Specify a valid provider." .Values.provider }}
  secretObjects:
  {{if .Values.secrets }}
  {{- range $k, $v := .Values.secrets}}                               # [OPTIONAL] SecretObject defines the desired state of synced K8s secret objects
  - secretName: {{ $k }}
    type: Opaque
    data: 
    - objectName: {{ $k }}
      key: {{ $v }}                    # name of the mounted content to sync. this could be the object name or object alias 
  {{- end }}
  {{- end }}
  
  {{- if .Values.parameters }}
  parameters:
    usePodIdentity: {{ .Values.parameters.usePodIdentity | quote }}
    useVMManagedIdentity: {{ .Values.parameters.useVMManagedIdentity | quote }}
    userAssignedIdentityID: {{ .Values.parameters.userAssignedIdentityID }}
    keyvaultName: {{ .Values.parameters.keyvaultName }}
    {{- if .Values.parameters.objects }}
    {{- with .Values.parameters.objects }}
    objects:
       {{- toYaml . | nindent 8 }}
     {{- end }}    
    {{- end}}
    tenantId: {{ .Values.parameters.tenantId }}
  {{- end }}
    